version: '3'

services:
  carepet-scylla:
    image: scylladb/scylla
    container_name: carepet-scylla1
    command: --smp 1

  carepet-scylla2:
    image: scylladb/scylla
    container_name: carepet-scylla2
    command: --smp 1 --seeds=carepet-scylla1

  carepet-scylla3:
    image: scylladb/scylla
    container_name: carepet-scylla3
    command: --smp 1 --seeds=carepet-scylla1
