#!/usr/bin/env php
<?php

use App\Core\Bootstrap;
use App\Core\Commands\Base\CommandException;
use App\Core\Commands\MigrateCommand;
use App\Core\Commands\ServeCommand;
use App\Core\Commands\SimulateCommand;

require_once 'vendor/autoload.php';

if(count($argv) <= 1) {
    echo "Please select a valid option" . PHP_EOL;
    return;
}
$container = (new Bootstrap())->init();
function getCommand($command)
{
    switch($command) {
        case 'serve':
            return ServeCommand::class;
        case 'migrate':
            return MigrateCommand::class;
        case 'simulate':
            return SimulateCommand::class;
    }

    throw CommandException::notFound($command);
}

$command = getCommand($argv[1]);
$container->call($command, ['args' => $argv]);
