name: "Docs / Amplify enhanced"

on: issue_comment

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Amplify enhanced
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: scylladb/sphinx-scylladb-theme/.github/actions/amplify-enhanced@master
